CREATE TABLE "VUEDM"."SYS_USER_ROLE"
(
 "USER_ID" BIGINT NOT NULL,
 "ROLE_ID" BIGINT NOT NULL
);

CREATE TABLE "VUEDM"."SYS_USER_POST"
(
 "USER_ID" BIGINT NOT NULL,
 "POST_ID" BIGINT NOT NULL
);

CREATE TABLE "VUEDM"."SYS_USER"
(
 "USER_ID" BIGINT IDENTITY(100,1) NOT NULL,
 "DEPT_ID" BIGINT NULL,
 "USER_NAME" VARCHAR(30) NOT NULL,
 "NICK_NAME" VARCHAR(30) NOT NULL,
 "USER_TYPE" VARCHAR(2) DEFAULT '00'
 NULL,
 "EMAIL" VARCHAR(50) DEFAULT ''
 NULL,
 "PHONENUMBER" VARCHAR(11) DEFAULT ''
 NULL,
 "SEX" CHAR(1) DEFAULT '0'
 NULL,
 "AVATAR" VARCHAR(100) DEFAULT ''
 NULL,
 "PASSWORD" VARCHAR(100) DEFAULT ''
 NULL,
 "STATUS" CHAR(1) DEFAULT '0'
 NULL,
 "DEL_FLAG" CHAR(1) DEFAULT '0'
 NULL,
 "LOGIN_IP" VARCHAR(128) DEFAULT ''
 NULL,
 "LOGIN_DATE" TIMESTAMP(0) NULL,
 "CREATE_BY" VARCHAR(64) DEFAULT ''
 NULL,
 "CREATE_TIME" TIMESTAMP(0) NULL,
 "UPDATE_BY" VARCHAR(64) DEFAULT ''
 NULL,
 "UPDATE_TIME" TIMESTAMP(0) NULL,
 "REMARK" VARCHAR(500) NULL
);

CREATE TABLE "VUEDM"."SYS_ROLE_MENU"
(
 "ROLE_ID" BIGINT NOT NULL,
 "MENU_ID" BIGINT NOT NULL
);

CREATE TABLE "VUEDM"."SYS_ROLE_DEPT"
(
 "ROLE_ID" BIGINT NOT NULL,
 "DEPT_ID" BIGINT NOT NULL
);

CREATE TABLE "VUEDM"."SYS_ROLE"
(
 "ROLE_ID" BIGINT IDENTITY(100,1) NOT NULL,
 "ROLE_NAME" VARCHAR(30) NOT NULL,
 "ROLE_KEY" VARCHAR(100) NOT NULL,
 "ROLE_SORT" INT NOT NULL,
 "DATA_SCOPE" CHAR(1) DEFAULT '1'
 NULL,
 "MENU_CHECK_STRICTLY" TINYINT DEFAULT 1
 NULL,
 "DEPT_CHECK_STRICTLY" TINYINT DEFAULT 1
 NULL,
 "STATUS" CHAR(1) NOT NULL,
 "DEL_FLAG" CHAR(1) DEFAULT '0'
 NULL,
 "CREATE_BY" VARCHAR(64) DEFAULT ''
 NULL,
 "CREATE_TIME" TIMESTAMP(0) NULL,
 "UPDATE_BY" VARCHAR(64) DEFAULT ''
 NULL,
 "UPDATE_TIME" TIMESTAMP(0) NULL,
 "REMARK" VARCHAR(500) NULL
);

CREATE TABLE "VUEDM"."SYS_POST"
(
 "POST_ID" BIGINT IDENTITY(4,1) NOT NULL,
 "POST_CODE" VARCHAR(64) NOT NULL,
 "POST_NAME" VARCHAR(50) NOT NULL,
 "POST_SORT" INT NOT NULL,
 "STATUS" CHAR(1) NOT NULL,
 "CREATE_BY" VARCHAR(64) DEFAULT ''
 NULL,
 "CREATE_TIME" TIMESTAMP(0) NULL,
 "UPDATE_BY" VARCHAR(64) DEFAULT ''
 NULL,
 "UPDATE_TIME" TIMESTAMP(0) NULL,
 "REMARK" VARCHAR(500) NULL
);

CREATE TABLE "VUEDM"."SYS_OPER_LOG"
(
 "OPER_ID" BIGINT IDENTITY(100,1) NOT NULL,
 "TITLE" VARCHAR(50) DEFAULT ''
 NULL,
 "BUSINESS_TYPE" INT DEFAULT 0
 NULL,
 "METHOD" VARCHAR(100) DEFAULT ''
 NULL,
 "REQUEST_METHOD" VARCHAR(10) DEFAULT ''
 NULL,
 "OPERATOR_TYPE" INT DEFAULT 0
 NULL,
 "OPER_NAME" VARCHAR(50) DEFAULT ''
 NULL,
 "DEPT_NAME" VARCHAR(50) DEFAULT ''
 NULL,
 "OPER_URL" VARCHAR(255) DEFAULT ''
 NULL,
 "OPER_IP" VARCHAR(128) DEFAULT ''
 NULL,
 "OPER_LOCATION" VARCHAR(255) DEFAULT ''
 NULL,
 "OPER_PARAM" CLOB DEFAULT ''
 NULL,
 "JSON_RESULT" VARCHAR(2000) DEFAULT ''
 NULL,
 "STATUS" INT DEFAULT 0
 NULL,
 "ERROR_MSG" VARCHAR(2000) DEFAULT ''
 NULL,
 "OPER_TIME" TIMESTAMP(0) NULL,
 "COST_TIME" BIGINT DEFAULT 0
 NULL
);

CREATE TABLE "VUEDM"."SYS_NOTICE"
(
 "NOTICE_ID" INT IDENTITY(10,1) NOT NULL,
 "NOTICE_TITLE" VARCHAR(50) NOT NULL,
 "NOTICE_TYPE" CHAR(1) NOT NULL,
 "NOTICE_CONTENT" BLOB NULL,
 "STATUS" CHAR(1) DEFAULT '0'
 NULL,
 "CREATE_BY" VARCHAR(64) DEFAULT ''
 NULL,
 "CREATE_TIME" TIMESTAMP(0) NULL,
 "UPDATE_BY" VARCHAR(64) DEFAULT ''
 NULL,
 "UPDATE_TIME" TIMESTAMP(0) NULL,
 "REMARK" VARCHAR(255) NULL
);

CREATE TABLE "VUEDM"."SYS_MENU"
(
 "MENU_ID" BIGINT IDENTITY(2000,1) NOT NULL,
 "MENU_NAME" VARCHAR(50) NOT NULL,
 "PARENT_ID" BIGINT DEFAULT 0
 NULL,
 "ORDER_NUM" INT DEFAULT 0
 NULL,
 "PATH" VARCHAR(200) DEFAULT ''
 NULL,
 "COMPONENT" VARCHAR(255) NULL,
 "QUERY" VARCHAR(255) NULL,
 "IS_FRAME" INT DEFAULT 1
 NULL,
 "IS_CACHE" INT DEFAULT 0
 NULL,
 "MENU_TYPE" CHAR(1) DEFAULT ''
 NULL,
 "VISIBLE" CHAR(1) DEFAULT '0'
 NULL,
 "STATUS" CHAR(1) DEFAULT '0'
 NULL,
 "PERMS" VARCHAR(100) NULL,
 "ICON" VARCHAR(100) DEFAULT '#'
 NULL,
 "CREATE_BY" VARCHAR(64) DEFAULT ''
 NULL,
 "CREATE_TIME" TIMESTAMP(0) NULL,
 "UPDATE_BY" VARCHAR(64) DEFAULT ''
 NULL,
 "UPDATE_TIME" TIMESTAMP(0) NULL,
 "REMARK" VARCHAR(500) DEFAULT ''
 NULL
);

CREATE TABLE "VUEDM"."SYS_LOGININFOR"
(
 "INFO_ID" BIGINT IDENTITY(100,1) NOT NULL,
 "USER_NAME" VARCHAR(50) DEFAULT ''
 NULL,
 "IPADDR" VARCHAR(128) DEFAULT ''
 NULL,
 "LOGIN_LOCATION" VARCHAR(255) DEFAULT ''
 NULL,
 "BROWSER" VARCHAR(50) DEFAULT ''
 NULL,
 "OS" VARCHAR(50) DEFAULT ''
 NULL,
 "STATUS" CHAR(1) DEFAULT '0'
 NULL,
 "MSG" VARCHAR(255) DEFAULT ''
 NULL,
 "LOGIN_TIME" TIMESTAMP(0) NULL
);

CREATE TABLE "VUEDM"."SYS_JOB_LOG"
(
 "JOB_LOG_ID" BIGINT IDENTITY(1,1) NOT NULL,
 "JOB_NAME" VARCHAR(64) NOT NULL,
 "JOB_GROUP" VARCHAR(64) NOT NULL,
 "INVOKE_TARGET" VARCHAR(500) NOT NULL,
 "JOB_MESSAGE" VARCHAR(500) NULL,
 "STATUS" CHAR(1) DEFAULT '0'
 NULL,
 "EXCEPTION_INFO" VARCHAR(2000) DEFAULT ''
 NULL,
 "CREATE_TIME" TIMESTAMP(0) NULL
);

CREATE TABLE "VUEDM"."SYS_JOB"
(
 "JOB_ID" BIGINT IDENTITY(100,1) NOT NULL,
 "JOB_NAME" VARCHAR(64) DEFAULT ''
 NOT NULL,
 "JOB_GROUP" VARCHAR(64) DEFAULT 'DEFAULT'
 NOT NULL,
 "INVOKE_TARGET" VARCHAR(500) NOT NULL,
 "CRON_EXPRESSION" VARCHAR(255) DEFAULT ''
 NULL,
 "MISFIRE_POLICY" VARCHAR(20) DEFAULT '3'
 NULL,
 "CONCURRENT" CHAR(1) DEFAULT '1'
 NULL,
 "STATUS" CHAR(1) DEFAULT '0'
 NULL,
 "CREATE_BY" VARCHAR(64) DEFAULT ''
 NULL,
 "CREATE_TIME" TIMESTAMP(0) NULL,
 "UPDATE_BY" VARCHAR(64) DEFAULT ''
 NULL,
 "UPDATE_TIME" TIMESTAMP(0) NULL,
 "REMARK" VARCHAR(500) DEFAULT ''
 NULL
);

CREATE TABLE "VUEDM"."SYS_DICT_TYPE"
(
 "DICT_ID" BIGINT IDENTITY(100,1) NOT NULL,
 "DICT_NAME" VARCHAR(100) DEFAULT ''
 NULL,
 "DICT_TYPE" VARCHAR(100) DEFAULT ''
 NULL,
 "STATUS" CHAR(1) DEFAULT '0'
 NULL,
 "CREATE_BY" VARCHAR(64) DEFAULT ''
 NULL,
 "CREATE_TIME" TIMESTAMP(0) NULL,
 "UPDATE_BY" VARCHAR(64) DEFAULT ''
 NULL,
 "UPDATE_TIME" TIMESTAMP(0) NULL,
 "REMARK" VARCHAR(500) NULL
);

CREATE TABLE "VUEDM"."SYS_DICT_DATA"
(
 "DICT_CODE" BIGINT IDENTITY(100,1) NOT NULL,
 "DICT_SORT" INT DEFAULT 0
 NULL,
 "DICT_LABEL" VARCHAR(100) DEFAULT ''
 NULL,
 "DICT_VALUE" VARCHAR(100) DEFAULT ''
 NULL,
 "DICT_TYPE" VARCHAR(100) DEFAULT ''
 NULL,
 "CSS_CLASS" VARCHAR(100) NULL,
 "LIST_CLASS" VARCHAR(100) NULL,
 "IS_DEFAULT" CHAR(1) DEFAULT 'N'
 NULL,
 "STATUS" CHAR(1) DEFAULT '0'
 NULL,
 "CREATE_BY" VARCHAR(64) DEFAULT ''
 NULL,
 "CREATE_TIME" TIMESTAMP(0) NULL,
 "UPDATE_BY" VARCHAR(64) DEFAULT ''
 NULL,
 "UPDATE_TIME" TIMESTAMP(0) NULL,
 "REMARK" VARCHAR(500) NULL
);

CREATE TABLE "VUEDM"."SYS_DEPT"
(
 "DEPT_ID" BIGINT IDENTITY(200,1) NOT NULL,
 "PARENT_ID" BIGINT DEFAULT 0
 NULL,
 "ANCESTORS" VARCHAR(50) DEFAULT ''
 NULL,
 "DEPT_NAME" VARCHAR(30) DEFAULT ''
 NULL,
 "ORDER_NUM" INT DEFAULT 0
 NULL,
 "LEADER" VARCHAR(20) NULL,
 "PHONE" VARCHAR(11) NULL,
 "EMAIL" VARCHAR(50) NULL,
 "STATUS" CHAR(1) DEFAULT '0'
 NULL,
 "DEL_FLAG" CHAR(1) DEFAULT '0'
 NULL,
 "CREATE_BY" VARCHAR(64) DEFAULT ''
 NULL,
 "CREATE_TIME" TIMESTAMP(0) NULL,
 "UPDATE_BY" VARCHAR(64) DEFAULT ''
 NULL,
 "UPDATE_TIME" TIMESTAMP(0) NULL
);

CREATE TABLE "VUEDM"."SYS_CONFIG"
(
 "CONFIG_ID" INT IDENTITY(100,1) NOT NULL,
 "CONFIG_NAME" VARCHAR(100) DEFAULT ''
 NULL,
 "CONFIG_KEY" VARCHAR(100) DEFAULT ''
 NULL,
 "CONFIG_VALUE" VARCHAR(500) DEFAULT ''
 NULL,
 "CONFIG_TYPE" CHAR(1) DEFAULT 'N'
 NULL,
 "CREATE_BY" VARCHAR(64) DEFAULT ''
 NULL,
 "CREATE_TIME" TIMESTAMP(0) NULL,
 "UPDATE_BY" VARCHAR(64) DEFAULT ''
 NULL,
 "UPDATE_TIME" TIMESTAMP(0) NULL,
 "REMARK" VARCHAR(500) NULL
);

CREATE TABLE "VUEDM"."GEN_TABLE_COLUMN"
(
 "COLUMN_ID" BIGINT IDENTITY(1,1) NOT NULL,
 "TABLE_ID" VARCHAR(64) NULL,
 "COLUMN_NAME" VARCHAR(200) NULL,
 "COLUMN_COMMENT" VARCHAR(500) NULL,
 "COLUMN_TYPE" VARCHAR(100) NULL,
 "JAVA_TYPE" VARCHAR(500) NULL,
 "JAVA_FIELD" VARCHAR(200) NULL,
 "IS_PK" CHAR(1) NULL,
 "IS_INCREMENT" CHAR(1) NULL,
 "IS_REQUIRED" CHAR(1) NULL,
 "IS_INSERT" CHAR(1) NULL,
 "IS_EDIT" CHAR(1) NULL,
 "IS_LIST" CHAR(1) NULL,
 "IS_QUERY" CHAR(1) NULL,
 "QUERY_TYPE" VARCHAR(200) DEFAULT 'EQ'
 NULL,
 "HTML_TYPE" VARCHAR(200) NULL,
 "DICT_TYPE" VARCHAR(200) DEFAULT ''
 NULL,
 "SORT" INT NULL,
 "CREATE_BY" VARCHAR(64) DEFAULT ''
 NULL,
 "CREATE_TIME" TIMESTAMP(0) NULL,
 "UPDATE_BY" VARCHAR(64) DEFAULT ''
 NULL,
 "UPDATE_TIME" TIMESTAMP(0) NULL
);

CREATE TABLE "VUEDM"."GEN_TABLE"
(
 "TABLE_ID" BIGINT IDENTITY(1,1) NOT NULL,
 "TABLE_NAME" VARCHAR(200) DEFAULT ''
 NULL,
 "TABLE_COMMENT" VARCHAR(500) DEFAULT ''
 NULL,
 "SUB_TABLE_NAME" VARCHAR(64) NULL,
 "SUB_TABLE_FK_NAME" VARCHAR(64) NULL,
 "CLASS_NAME" VARCHAR(100) DEFAULT ''
 NULL,
 "TPL_CATEGORY" VARCHAR(200) DEFAULT 'crud'
 NULL,
 "PACKAGE_NAME" VARCHAR(100) NULL,
 "MODULE_NAME" VARCHAR(30) NULL,
 "BUSINESS_NAME" VARCHAR(30) NULL,
 "FUNCTION_NAME" VARCHAR(50) NULL,
 "FUNCTION_AUTHOR" VARCHAR(50) NULL,
 "GEN_TYPE" CHAR(1) DEFAULT '0'
 NULL,
 "GEN_PATH" VARCHAR(200) DEFAULT '/'
 NULL,
 "OPTIONS" VARCHAR(1000) NULL,
 "CREATE_BY" VARCHAR(64) DEFAULT ''
 NULL,
 "CREATE_TIME" TIMESTAMP(0) NULL,
 "UPDATE_BY" VARCHAR(64) DEFAULT ''
 NULL,
 "UPDATE_TIME" TIMESTAMP(0) NULL,
 "REMARK" VARCHAR(500) NULL
);

CREATE TABLE "VUEDM"."DATA_TEST"
(
 "ID" VARCHAR(50) NOT NULL,
 "CESHI" VARCHAR(50) NULL,
 "SEX" CHAR(1) NULL,
 "MONEY" INT NULL,
  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE  FUNCTION "VUEDM"."FIND_IN_SET"
                (
                        piv_str1 varchar2,
                        piv_str2 varchar2,
                        p_sep    varchar2 := ',')
                RETURN NUMBER
                            IS
                l_idx     number:=0;                 -- 用于计算piv_str2中分隔符的位置
                str       varchar2(500);             -- 根据分隔符截取的子字符串
                piv_str   varchar2(500) := piv_str2; -- 将piv_str2赋值给piv_str
                res       number        :=0;         -- 返回结果
                loopIndex number        :=0;
        BEGIN
                -- 如果piv_str中没有分割符，直接判断piv_str1和piv_str是否相等，相等 res=1
                IF instr(piv_str, p_sep, 1) = 0 THEN
                        IF piv_str          = piv_str1 THEN
                                res        := 1;
                        END IF;
                ELSE
                        -- 循环按分隔符截取piv_str
                        LOOP
                                l_idx    := instr(piv_str, p_sep);
                                loopIndex:=loopIndex+1;
                                -- 当piv_str中还有分隔符时
                                IF l_idx > 0 THEN
                                        -- 截取第一个分隔符前的字段str
                                        str:= substr(piv_str, 1, l_idx-1);
                                        -- 判断 str 和piv_str1 是否相等，相等 res=1 并结束循环判断
                                        IF str      = piv_str1 THEN
                                                res:= loopIndex;
                                                EXIT;
                                        END IF;
                                        piv_str := substr(piv_str, l_idx+length(p_sep));
                                ELSE
                                        -- 当截取后的piv_str 中不存在分割符时，判断piv_str和piv_str1是否相等，相等 res=1
                                        IF piv_str  = piv_str1 THEN
                                                res:= loopIndex;
                                        END IF;
                                        -- 无论最后是否相等，都跳出循环
                                        EXIT;
                                END IF;
                        END LOOP;
                        -- 结束循环
                END IF;
                -- 返回res
                RETURN res;
        END FIND_IN_SET;

ALTER TABLE "VUEDM"."SYS_USER_ROLE" ADD CONSTRAINT  PRIMARY KEY("USER_ID","ROLE_ID") ;

ALTER TABLE "VUEDM"."SYS_USER_POST" ADD CONSTRAINT  PRIMARY KEY("USER_ID","POST_ID") ;

ALTER TABLE "VUEDM"."SYS_USER" ADD CONSTRAINT  PRIMARY KEY("USER_ID") ;

ALTER TABLE "VUEDM"."SYS_ROLE_MENU" ADD CONSTRAINT  PRIMARY KEY("ROLE_ID","MENU_ID") ;

ALTER TABLE "VUEDM"."SYS_ROLE_DEPT" ADD CONSTRAINT  PRIMARY KEY("ROLE_ID","DEPT_ID") ;

ALTER TABLE "VUEDM"."SYS_ROLE" ADD CONSTRAINT  PRIMARY KEY("ROLE_ID") ;

ALTER TABLE "VUEDM"."SYS_POST" ADD CONSTRAINT  PRIMARY KEY("POST_ID") ;

ALTER TABLE "VUEDM"."SYS_OPER_LOG" ADD CONSTRAINT  PRIMARY KEY("OPER_ID") ;

ALTER TABLE "VUEDM"."SYS_NOTICE" ADD CONSTRAINT  PRIMARY KEY("NOTICE_ID") ;

ALTER TABLE "VUEDM"."SYS_MENU" ADD CONSTRAINT  PRIMARY KEY("MENU_ID") ;

ALTER TABLE "VUEDM"."SYS_LOGININFOR" ADD CONSTRAINT  PRIMARY KEY("INFO_ID") ;

ALTER TABLE "VUEDM"."SYS_JOB_LOG" ADD CONSTRAINT  PRIMARY KEY("JOB_LOG_ID") ;

ALTER TABLE "VUEDM"."SYS_JOB" ADD CONSTRAINT  PRIMARY KEY("JOB_ID","JOB_NAME","JOB_GROUP") ;

ALTER TABLE "VUEDM"."SYS_DICT_TYPE" ADD CONSTRAINT  PRIMARY KEY("DICT_ID") ;

ALTER TABLE "VUEDM"."SYS_DICT_TYPE" ADD CONSTRAINT "DICT_TYPE" UNIQUE("DICT_TYPE") ;

ALTER TABLE "VUEDM"."SYS_DICT_DATA" ADD CONSTRAINT  PRIMARY KEY("DICT_CODE") ;

ALTER TABLE "VUEDM"."SYS_DEPT" ADD CONSTRAINT  PRIMARY KEY("DEPT_ID") ;

ALTER TABLE "VUEDM"."SYS_CONFIG" ADD CONSTRAINT  PRIMARY KEY("CONFIG_ID") ;

ALTER TABLE "VUEDM"."GEN_TABLE_COLUMN" ADD CONSTRAINT  PRIMARY KEY("COLUMN_ID") ;

ALTER TABLE "VUEDM"."GEN_TABLE" ADD CONSTRAINT  PRIMARY KEY("TABLE_ID") ;

COMMENT ON TABLE "VUEDM"."SYS_USER_ROLE" IS '用户和角色关联表';

COMMENT ON COLUMN "VUEDM"."SYS_USER_ROLE"."USER_ID" IS '用户ID';

COMMENT ON COLUMN "VUEDM"."SYS_USER_ROLE"."ROLE_ID" IS '角色ID';

COMMENT ON TABLE "VUEDM"."SYS_USER_POST" IS '用户与岗位关联表';

COMMENT ON COLUMN "VUEDM"."SYS_USER_POST"."USER_ID" IS '用户ID';

COMMENT ON COLUMN "VUEDM"."SYS_USER_POST"."POST_ID" IS '岗位ID';

COMMENT ON TABLE "VUEDM"."SYS_USER" IS '用户信息表';

COMMENT ON COLUMN "VUEDM"."SYS_USER"."USER_ID" IS '用户ID';

COMMENT ON COLUMN "VUEDM"."SYS_USER"."DEPT_ID" IS '部门ID';

COMMENT ON COLUMN "VUEDM"."SYS_USER"."USER_NAME" IS '用户账号';

COMMENT ON COLUMN "VUEDM"."SYS_USER"."NICK_NAME" IS '用户昵称';

COMMENT ON COLUMN "VUEDM"."SYS_USER"."USER_TYPE" IS '用户类型（00系统用户）';

COMMENT ON COLUMN "VUEDM"."SYS_USER"."EMAIL" IS '用户邮箱';

COMMENT ON COLUMN "VUEDM"."SYS_USER"."PHONENUMBER" IS '手机号码';

COMMENT ON COLUMN "VUEDM"."SYS_USER"."SEX" IS '用户性别（0男 1女 2未知）';

COMMENT ON COLUMN "VUEDM"."SYS_USER"."AVATAR" IS '头像地址';

COMMENT ON COLUMN "VUEDM"."SYS_USER"."PASSWORD" IS '密码';

COMMENT ON COLUMN "VUEDM"."SYS_USER"."STATUS" IS '帐号状态（0正常 1停用）';

COMMENT ON COLUMN "VUEDM"."SYS_USER"."DEL_FLAG" IS '删除标志（0代表存在 2代表删除）';

COMMENT ON COLUMN "VUEDM"."SYS_USER"."LOGIN_IP" IS '最后登录IP';

COMMENT ON COLUMN "VUEDM"."SYS_USER"."LOGIN_DATE" IS '最后登录时间';

COMMENT ON COLUMN "VUEDM"."SYS_USER"."CREATE_BY" IS '创建者';

COMMENT ON COLUMN "VUEDM"."SYS_USER"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "VUEDM"."SYS_USER"."UPDATE_BY" IS '更新者';

COMMENT ON COLUMN "VUEDM"."SYS_USER"."UPDATE_TIME" IS '更新时间';

COMMENT ON COLUMN "VUEDM"."SYS_USER"."REMARK" IS '备注';

COMMENT ON TABLE "VUEDM"."SYS_ROLE_MENU" IS '角色和菜单关联表';

COMMENT ON COLUMN "VUEDM"."SYS_ROLE_MENU"."ROLE_ID" IS '角色ID';

COMMENT ON COLUMN "VUEDM"."SYS_ROLE_MENU"."MENU_ID" IS '菜单ID';

COMMENT ON TABLE "VUEDM"."SYS_ROLE_DEPT" IS '角色和部门关联表';

COMMENT ON COLUMN "VUEDM"."SYS_ROLE_DEPT"."ROLE_ID" IS '角色ID';

COMMENT ON COLUMN "VUEDM"."SYS_ROLE_DEPT"."DEPT_ID" IS '部门ID';

COMMENT ON TABLE "VUEDM"."SYS_ROLE" IS '角色信息表';

COMMENT ON COLUMN "VUEDM"."SYS_ROLE"."ROLE_ID" IS '角色ID';

COMMENT ON COLUMN "VUEDM"."SYS_ROLE"."ROLE_NAME" IS '角色名称';

COMMENT ON COLUMN "VUEDM"."SYS_ROLE"."ROLE_KEY" IS '角色权限字符串';

COMMENT ON COLUMN "VUEDM"."SYS_ROLE"."ROLE_SORT" IS '显示顺序';

COMMENT ON COLUMN "VUEDM"."SYS_ROLE"."DATA_SCOPE" IS '数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限）';

COMMENT ON COLUMN "VUEDM"."SYS_ROLE"."MENU_CHECK_STRICTLY" IS '菜单树选择项是否关联显示';

COMMENT ON COLUMN "VUEDM"."SYS_ROLE"."DEPT_CHECK_STRICTLY" IS '部门树选择项是否关联显示';

COMMENT ON COLUMN "VUEDM"."SYS_ROLE"."STATUS" IS '角色状态（0正常 1停用）';

COMMENT ON COLUMN "VUEDM"."SYS_ROLE"."DEL_FLAG" IS '删除标志（0代表存在 2代表删除）';

COMMENT ON COLUMN "VUEDM"."SYS_ROLE"."CREATE_BY" IS '创建者';

COMMENT ON COLUMN "VUEDM"."SYS_ROLE"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "VUEDM"."SYS_ROLE"."UPDATE_BY" IS '更新者';

COMMENT ON COLUMN "VUEDM"."SYS_ROLE"."UPDATE_TIME" IS '更新时间';

COMMENT ON COLUMN "VUEDM"."SYS_ROLE"."REMARK" IS '备注';

COMMENT ON TABLE "VUEDM"."SYS_POST" IS '岗位信息表';

COMMENT ON COLUMN "VUEDM"."SYS_POST"."POST_ID" IS '岗位ID';

COMMENT ON COLUMN "VUEDM"."SYS_POST"."POST_CODE" IS '岗位编码';

COMMENT ON COLUMN "VUEDM"."SYS_POST"."POST_NAME" IS '岗位名称';

COMMENT ON COLUMN "VUEDM"."SYS_POST"."POST_SORT" IS '显示顺序';

COMMENT ON COLUMN "VUEDM"."SYS_POST"."STATUS" IS '状态（0正常 1停用）';

COMMENT ON COLUMN "VUEDM"."SYS_POST"."CREATE_BY" IS '创建者';

COMMENT ON COLUMN "VUEDM"."SYS_POST"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "VUEDM"."SYS_POST"."UPDATE_BY" IS '更新者';

COMMENT ON COLUMN "VUEDM"."SYS_POST"."UPDATE_TIME" IS '更新时间';

COMMENT ON COLUMN "VUEDM"."SYS_POST"."REMARK" IS '备注';

CREATE INDEX "IDX_SYS_OPER_LOG_BT"
ON "VUEDM"."SYS_OPER_LOG"("BUSINESS_TYPE");

CREATE INDEX "IDX_SYS_OPER_LOG_S"
ON "VUEDM"."SYS_OPER_LOG"("STATUS");

CREATE INDEX "IDX_SYS_OPER_LOG_OT"
ON "VUEDM"."SYS_OPER_LOG"("OPER_TIME");

COMMENT ON TABLE "VUEDM"."SYS_OPER_LOG" IS '操作日志记录';

COMMENT ON COLUMN "VUEDM"."SYS_OPER_LOG"."OPER_ID" IS '日志主键';

COMMENT ON COLUMN "VUEDM"."SYS_OPER_LOG"."TITLE" IS '模块标题';

COMMENT ON COLUMN "VUEDM"."SYS_OPER_LOG"."BUSINESS_TYPE" IS '业务类型（0其它 1新增 2修改 3删除）';

COMMENT ON COLUMN "VUEDM"."SYS_OPER_LOG"."METHOD" IS '方法名称';

COMMENT ON COLUMN "VUEDM"."SYS_OPER_LOG"."REQUEST_METHOD" IS '请求方式';

COMMENT ON COLUMN "VUEDM"."SYS_OPER_LOG"."OPERATOR_TYPE" IS '操作类别（0其它 1后台用户 2手机端用户）';

COMMENT ON COLUMN "VUEDM"."SYS_OPER_LOG"."OPER_NAME" IS '操作人员';

COMMENT ON COLUMN "VUEDM"."SYS_OPER_LOG"."DEPT_NAME" IS '部门名称';

COMMENT ON COLUMN "VUEDM"."SYS_OPER_LOG"."OPER_URL" IS '请求URL';

COMMENT ON COLUMN "VUEDM"."SYS_OPER_LOG"."OPER_IP" IS '主机地址';

COMMENT ON COLUMN "VUEDM"."SYS_OPER_LOG"."OPER_LOCATION" IS '操作地点';

COMMENT ON COLUMN "VUEDM"."SYS_OPER_LOG"."OPER_PARAM" IS '请求参数';

COMMENT ON COLUMN "VUEDM"."SYS_OPER_LOG"."JSON_RESULT" IS '返回参数';

COMMENT ON COLUMN "VUEDM"."SYS_OPER_LOG"."STATUS" IS '操作状态（0正常 1异常）';

COMMENT ON COLUMN "VUEDM"."SYS_OPER_LOG"."ERROR_MSG" IS '错误消息';

COMMENT ON COLUMN "VUEDM"."SYS_OPER_LOG"."OPER_TIME" IS '操作时间';

COMMENT ON COLUMN "VUEDM"."SYS_OPER_LOG"."COST_TIME" IS '消耗时间';

COMMENT ON TABLE "VUEDM"."SYS_NOTICE" IS '通知公告表';

COMMENT ON COLUMN "VUEDM"."SYS_NOTICE"."NOTICE_ID" IS '公告ID';

COMMENT ON COLUMN "VUEDM"."SYS_NOTICE"."NOTICE_TITLE" IS '公告标题';

COMMENT ON COLUMN "VUEDM"."SYS_NOTICE"."NOTICE_TYPE" IS '公告类型（1通知 2公告）';

COMMENT ON COLUMN "VUEDM"."SYS_NOTICE"."NOTICE_CONTENT" IS '公告内容';

COMMENT ON COLUMN "VUEDM"."SYS_NOTICE"."STATUS" IS '公告状态（0正常 1关闭）';

COMMENT ON COLUMN "VUEDM"."SYS_NOTICE"."CREATE_BY" IS '创建者';

COMMENT ON COLUMN "VUEDM"."SYS_NOTICE"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "VUEDM"."SYS_NOTICE"."UPDATE_BY" IS '更新者';

COMMENT ON COLUMN "VUEDM"."SYS_NOTICE"."UPDATE_TIME" IS '更新时间';

COMMENT ON COLUMN "VUEDM"."SYS_NOTICE"."REMARK" IS '备注';

COMMENT ON TABLE "VUEDM"."SYS_MENU" IS '菜单权限表';

COMMENT ON COLUMN "VUEDM"."SYS_MENU"."MENU_ID" IS '菜单ID';

COMMENT ON COLUMN "VUEDM"."SYS_MENU"."MENU_NAME" IS '菜单名称';

COMMENT ON COLUMN "VUEDM"."SYS_MENU"."PARENT_ID" IS '父菜单ID';

COMMENT ON COLUMN "VUEDM"."SYS_MENU"."ORDER_NUM" IS '显示顺序';

COMMENT ON COLUMN "VUEDM"."SYS_MENU"."PATH" IS '路由地址';

COMMENT ON COLUMN "VUEDM"."SYS_MENU"."COMPONENT" IS '组件路径';

COMMENT ON COLUMN "VUEDM"."SYS_MENU"."QUERY" IS '路由参数';

COMMENT ON COLUMN "VUEDM"."SYS_MENU"."IS_FRAME" IS '是否为外链（0是 1否）';

COMMENT ON COLUMN "VUEDM"."SYS_MENU"."IS_CACHE" IS '是否缓存（0缓存 1不缓存）';

COMMENT ON COLUMN "VUEDM"."SYS_MENU"."MENU_TYPE" IS '菜单类型（M目录 C菜单 F按钮）';

COMMENT ON COLUMN "VUEDM"."SYS_MENU"."VISIBLE" IS '菜单状态（0显示 1隐藏）';

COMMENT ON COLUMN "VUEDM"."SYS_MENU"."STATUS" IS '菜单状态（0正常 1停用）';

COMMENT ON COLUMN "VUEDM"."SYS_MENU"."PERMS" IS '权限标识';

COMMENT ON COLUMN "VUEDM"."SYS_MENU"."ICON" IS '菜单图标';

COMMENT ON COLUMN "VUEDM"."SYS_MENU"."CREATE_BY" IS '创建者';

COMMENT ON COLUMN "VUEDM"."SYS_MENU"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "VUEDM"."SYS_MENU"."UPDATE_BY" IS '更新者';

COMMENT ON COLUMN "VUEDM"."SYS_MENU"."UPDATE_TIME" IS '更新时间';

COMMENT ON COLUMN "VUEDM"."SYS_MENU"."REMARK" IS '备注';

CREATE INDEX "IDX_SYS_LOGININFOR_LT"
ON "VUEDM"."SYS_LOGININFOR"("LOGIN_TIME");

CREATE INDEX "IDX_SYS_LOGININFOR_S"
ON "VUEDM"."SYS_LOGININFOR"("STATUS");

COMMENT ON TABLE "VUEDM"."SYS_LOGININFOR" IS '系统访问记录';

COMMENT ON COLUMN "VUEDM"."SYS_LOGININFOR"."INFO_ID" IS '访问ID';

COMMENT ON COLUMN "VUEDM"."SYS_LOGININFOR"."USER_NAME" IS '用户账号';

COMMENT ON COLUMN "VUEDM"."SYS_LOGININFOR"."IPADDR" IS '登录IP地址';

COMMENT ON COLUMN "VUEDM"."SYS_LOGININFOR"."LOGIN_LOCATION" IS '登录地点';

COMMENT ON COLUMN "VUEDM"."SYS_LOGININFOR"."BROWSER" IS '浏览器类型';

COMMENT ON COLUMN "VUEDM"."SYS_LOGININFOR"."OS" IS '操作系统';

COMMENT ON COLUMN "VUEDM"."SYS_LOGININFOR"."STATUS" IS '登录状态（0成功 1失败）';

COMMENT ON COLUMN "VUEDM"."SYS_LOGININFOR"."MSG" IS '提示消息';

COMMENT ON COLUMN "VUEDM"."SYS_LOGININFOR"."LOGIN_TIME" IS '访问时间';

COMMENT ON TABLE "VUEDM"."SYS_JOB_LOG" IS '定时任务调度日志表';

COMMENT ON COLUMN "VUEDM"."SYS_JOB_LOG"."JOB_LOG_ID" IS '任务日志ID';

COMMENT ON COLUMN "VUEDM"."SYS_JOB_LOG"."JOB_NAME" IS '任务名称';

COMMENT ON COLUMN "VUEDM"."SYS_JOB_LOG"."JOB_GROUP" IS '任务组名';

COMMENT ON COLUMN "VUEDM"."SYS_JOB_LOG"."INVOKE_TARGET" IS '调用目标字符串';

COMMENT ON COLUMN "VUEDM"."SYS_JOB_LOG"."JOB_MESSAGE" IS '日志信息';

COMMENT ON COLUMN "VUEDM"."SYS_JOB_LOG"."STATUS" IS '执行状态（0正常 1失败）';

COMMENT ON COLUMN "VUEDM"."SYS_JOB_LOG"."EXCEPTION_INFO" IS '异常信息';

COMMENT ON COLUMN "VUEDM"."SYS_JOB_LOG"."CREATE_TIME" IS '创建时间';

COMMENT ON TABLE "VUEDM"."SYS_JOB" IS '定时任务调度表';

COMMENT ON COLUMN "VUEDM"."SYS_JOB"."JOB_ID" IS '任务ID';

COMMENT ON COLUMN "VUEDM"."SYS_JOB"."JOB_NAME" IS '任务名称';

COMMENT ON COLUMN "VUEDM"."SYS_JOB"."JOB_GROUP" IS '任务组名';

COMMENT ON COLUMN "VUEDM"."SYS_JOB"."INVOKE_TARGET" IS '调用目标字符串';

COMMENT ON COLUMN "VUEDM"."SYS_JOB"."CRON_EXPRESSION" IS 'cron执行表达式';

COMMENT ON COLUMN "VUEDM"."SYS_JOB"."MISFIRE_POLICY" IS '计划执行错误策略（1立即执行 2执行一次 3放弃执行）';

COMMENT ON COLUMN "VUEDM"."SYS_JOB"."CONCURRENT" IS '是否并发执行（0允许 1禁止）';

COMMENT ON COLUMN "VUEDM"."SYS_JOB"."STATUS" IS '状态（0正常 1暂停）';

COMMENT ON COLUMN "VUEDM"."SYS_JOB"."CREATE_BY" IS '创建者';

COMMENT ON COLUMN "VUEDM"."SYS_JOB"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "VUEDM"."SYS_JOB"."UPDATE_BY" IS '更新者';

COMMENT ON COLUMN "VUEDM"."SYS_JOB"."UPDATE_TIME" IS '更新时间';

COMMENT ON COLUMN "VUEDM"."SYS_JOB"."REMARK" IS '备注信息';

COMMENT ON TABLE "VUEDM"."SYS_DICT_TYPE" IS '字典类型表';

COMMENT ON COLUMN "VUEDM"."SYS_DICT_TYPE"."DICT_ID" IS '字典主键';

COMMENT ON COLUMN "VUEDM"."SYS_DICT_TYPE"."DICT_NAME" IS '字典名称';

COMMENT ON COLUMN "VUEDM"."SYS_DICT_TYPE"."DICT_TYPE" IS '字典类型';

COMMENT ON COLUMN "VUEDM"."SYS_DICT_TYPE"."STATUS" IS '状态（0正常 1停用）';

COMMENT ON COLUMN "VUEDM"."SYS_DICT_TYPE"."CREATE_BY" IS '创建者';

COMMENT ON COLUMN "VUEDM"."SYS_DICT_TYPE"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "VUEDM"."SYS_DICT_TYPE"."UPDATE_BY" IS '更新者';

COMMENT ON COLUMN "VUEDM"."SYS_DICT_TYPE"."UPDATE_TIME" IS '更新时间';

COMMENT ON COLUMN "VUEDM"."SYS_DICT_TYPE"."REMARK" IS '备注';

COMMENT ON TABLE "VUEDM"."SYS_DICT_DATA" IS '字典数据表';

COMMENT ON COLUMN "VUEDM"."SYS_DICT_DATA"."DICT_CODE" IS '字典编码';

COMMENT ON COLUMN "VUEDM"."SYS_DICT_DATA"."DICT_SORT" IS '字典排序';

COMMENT ON COLUMN "VUEDM"."SYS_DICT_DATA"."DICT_LABEL" IS '字典标签';

COMMENT ON COLUMN "VUEDM"."SYS_DICT_DATA"."DICT_VALUE" IS '字典键值';

COMMENT ON COLUMN "VUEDM"."SYS_DICT_DATA"."DICT_TYPE" IS '字典类型';

COMMENT ON COLUMN "VUEDM"."SYS_DICT_DATA"."CSS_CLASS" IS '样式属性（其他样式扩展）';

COMMENT ON COLUMN "VUEDM"."SYS_DICT_DATA"."LIST_CLASS" IS '表格回显样式';

COMMENT ON COLUMN "VUEDM"."SYS_DICT_DATA"."IS_DEFAULT" IS '是否默认（Y是 N否）';

COMMENT ON COLUMN "VUEDM"."SYS_DICT_DATA"."STATUS" IS '状态（0正常 1停用）';

COMMENT ON COLUMN "VUEDM"."SYS_DICT_DATA"."CREATE_BY" IS '创建者';

COMMENT ON COLUMN "VUEDM"."SYS_DICT_DATA"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "VUEDM"."SYS_DICT_DATA"."UPDATE_BY" IS '更新者';

COMMENT ON COLUMN "VUEDM"."SYS_DICT_DATA"."UPDATE_TIME" IS '更新时间';

COMMENT ON COLUMN "VUEDM"."SYS_DICT_DATA"."REMARK" IS '备注';

COMMENT ON TABLE "VUEDM"."SYS_DEPT" IS '部门表';

COMMENT ON COLUMN "VUEDM"."SYS_DEPT"."DEPT_ID" IS '部门id';

COMMENT ON COLUMN "VUEDM"."SYS_DEPT"."PARENT_ID" IS '父部门id';

COMMENT ON COLUMN "VUEDM"."SYS_DEPT"."ANCESTORS" IS '祖级列表';

COMMENT ON COLUMN "VUEDM"."SYS_DEPT"."DEPT_NAME" IS '部门名称';

COMMENT ON COLUMN "VUEDM"."SYS_DEPT"."ORDER_NUM" IS '显示顺序';

COMMENT ON COLUMN "VUEDM"."SYS_DEPT"."LEADER" IS '负责人';

COMMENT ON COLUMN "VUEDM"."SYS_DEPT"."PHONE" IS '联系电话';

COMMENT ON COLUMN "VUEDM"."SYS_DEPT"."EMAIL" IS '邮箱';

COMMENT ON COLUMN "VUEDM"."SYS_DEPT"."STATUS" IS '部门状态（0正常 1停用）';

COMMENT ON COLUMN "VUEDM"."SYS_DEPT"."DEL_FLAG" IS '删除标志（0代表存在 2代表删除）';

COMMENT ON COLUMN "VUEDM"."SYS_DEPT"."CREATE_BY" IS '创建者';

COMMENT ON COLUMN "VUEDM"."SYS_DEPT"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "VUEDM"."SYS_DEPT"."UPDATE_BY" IS '更新者';

COMMENT ON COLUMN "VUEDM"."SYS_DEPT"."UPDATE_TIME" IS '更新时间';

COMMENT ON TABLE "VUEDM"."SYS_CONFIG" IS '参数配置表';

COMMENT ON COLUMN "VUEDM"."SYS_CONFIG"."CONFIG_ID" IS '参数主键';

COMMENT ON COLUMN "VUEDM"."SYS_CONFIG"."CONFIG_NAME" IS '参数名称';

COMMENT ON COLUMN "VUEDM"."SYS_CONFIG"."CONFIG_KEY" IS '参数键名';

COMMENT ON COLUMN "VUEDM"."SYS_CONFIG"."CONFIG_VALUE" IS '参数键值';

COMMENT ON COLUMN "VUEDM"."SYS_CONFIG"."CONFIG_TYPE" IS '系统内置（Y是 N否）';

COMMENT ON COLUMN "VUEDM"."SYS_CONFIG"."CREATE_BY" IS '创建者';

COMMENT ON COLUMN "VUEDM"."SYS_CONFIG"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "VUEDM"."SYS_CONFIG"."UPDATE_BY" IS '更新者';

COMMENT ON COLUMN "VUEDM"."SYS_CONFIG"."UPDATE_TIME" IS '更新时间';

COMMENT ON COLUMN "VUEDM"."SYS_CONFIG"."REMARK" IS '备注';

COMMENT ON TABLE "VUEDM"."GEN_TABLE_COLUMN" IS '代码生成业务表字段';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE_COLUMN"."COLUMN_ID" IS '编号';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE_COLUMN"."TABLE_ID" IS '归属表编号';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE_COLUMN"."COLUMN_NAME" IS '列名称';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE_COLUMN"."COLUMN_COMMENT" IS '列描述';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE_COLUMN"."COLUMN_TYPE" IS '列类型';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE_COLUMN"."JAVA_TYPE" IS 'JAVA类型';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE_COLUMN"."JAVA_FIELD" IS 'JAVA字段名';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE_COLUMN"."IS_PK" IS '是否主键（1是）';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE_COLUMN"."IS_INCREMENT" IS '是否自增（1是）';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE_COLUMN"."IS_REQUIRED" IS '是否必填（1是）';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE_COLUMN"."IS_INSERT" IS '是否为插入字段（1是）';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE_COLUMN"."IS_EDIT" IS '是否编辑字段（1是）';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE_COLUMN"."IS_LIST" IS '是否列表字段（1是）';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE_COLUMN"."IS_QUERY" IS '是否查询字段（1是）';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE_COLUMN"."QUERY_TYPE" IS '查询方式（等于、不等于、大于、小于、范围）';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE_COLUMN"."HTML_TYPE" IS '显示类型（文本框、文本域、下拉框、复选框、单选框、日期控件）';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE_COLUMN"."DICT_TYPE" IS '字典类型';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE_COLUMN"."SORT" IS '排序';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE_COLUMN"."CREATE_BY" IS '创建者';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE_COLUMN"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE_COLUMN"."UPDATE_BY" IS '更新者';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE_COLUMN"."UPDATE_TIME" IS '更新时间';

COMMENT ON TABLE "VUEDM"."GEN_TABLE" IS '代码生成业务表';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE"."TABLE_ID" IS '编号';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE"."TABLE_NAME" IS '表名称';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE"."TABLE_COMMENT" IS '表描述';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE"."SUB_TABLE_NAME" IS '关联子表的表名';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE"."SUB_TABLE_FK_NAME" IS '子表关联的外键名';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE"."CLASS_NAME" IS '实体类名称';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE"."TPL_CATEGORY" IS '使用的模板（crud单表操作 tree树表操作）';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE"."PACKAGE_NAME" IS '生成包路径';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE"."MODULE_NAME" IS '生成模块名';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE"."BUSINESS_NAME" IS '生成业务名';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE"."FUNCTION_NAME" IS '生成功能名';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE"."FUNCTION_AUTHOR" IS '生成功能作者';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE"."GEN_TYPE" IS '生成代码方式（0zip压缩包 1自定义路径）';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE"."GEN_PATH" IS '生成路径（不填默认项目路径）';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE"."OPTIONS" IS '其它生成选项';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE"."CREATE_BY" IS '创建者';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE"."UPDATE_BY" IS '更新者';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE"."UPDATE_TIME" IS '更新时间';

COMMENT ON COLUMN "VUEDM"."GEN_TABLE"."REMARK" IS '备注';

COMMENT ON TABLE "VUEDM"."DATA_TEST" IS '测试表';

COMMENT ON COLUMN "VUEDM"."DATA_TEST"."ID" IS '主键';

COMMENT ON COLUMN "VUEDM"."DATA_TEST"."CESHI" IS 's';

COMMENT ON COLUMN "VUEDM"."DATA_TEST"."SEX" IS 's';

COMMENT ON COLUMN "VUEDM"."DATA_TEST"."MONEY" IS 's';

